### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by rahulrawat** [chiragjain/Emoticons-Keyboard#2]
HI ,

first of all thank you for your project.

I am creating a chat application and it was very usefull for me. but for outgoing message , it is working good . and when incoming message is come, i am unable to get smile .

please suggest me how can i do it?

thank you

**Comment by chiragjain** [comment]
Hi Rahul,
For outgoing and incoming messages, you should use some key-word for your
smileys and map them with your emoticons images in your app.
e.g. [:)], [:P], [:D] etc.

and thanks for appreciation.

On Fri, Sep 6, 2013 at 4:11 PM, rahulrawat notifications@github.com wrote:

> HI ,
> 
> first of all thank you for your project.
> 
> I am creating a chat application and it was very usefull for me. but for
> outgoing message , it is working good . and when incoming message is come,
> i am unable to get smile .
> 
> please suggest me how can i do it?
> 
> thank you
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chiragjain/Emoticons-Keyboard/issues/2
> .

## Regards,

_Chirag Jain_
Contact : _+91-9582841661_

**Comment by rahulrawat** [comment]
Thank you very much for your reply.
